### ISSUE TITLE
(Question) Docker DumpVDL2

### ISSUE THREAD

**Issue by alphafox02** [sdr-enthusiasts/docker-acarshub#1035]
When running docker-acarshub and the docker-vdl2, would the SERVER for vdl2 be 172.17.0.1 (for example) or is it okay that it's saying --output decoded:json:udp:address=127.0.0.1,port=5555?

At first I was getting a socat warning every so often and I wasn't sure why. I went and in the docker for vdl2, I put SERVER= and left it blank. 

Just trying to clarify what settings should be in place. I can see that I'm getting acars vhf messages to the acars hub, but I haven't seen anything that would appear to be marked as vdl2 messages (no freqs I've set) although I am sometimes getting vdl2 messages.

**Comment by fredclausen** [comment]
The answer to the question depends on a few things

1) Are you using `acars_router`?
2) Are you using `docker-vdlm2dec` or `docker-dumpvdl2`?

I'm assuming by that `output` line you're using dumpvdl2. 

If you are NOT using acars_router:

* Remove the `SERVER` line from your dumpvdl2 config, or alternatively set it to `acarshub`
* Make sure `ENABLE_VDLM=EXTERNAL` is set under ACARS Hub's environment.

If you are using acars_router

* Set the `SERVER` line to blank `- SERVER=`
* Make sure `ENABLE_VDLM=EXTERNAL` is set under ACARS Hub's environment.
* Under acars_router's environment set `- AR_RECV_ZMQ_VDLM2=dumpvdl2:45555` and `- AR_SEND_UDP_VDLM2=acarshub:5555`

**Comment by alphafox02** [comment]
Thank you for the fast response. I'm using docker-dumpvdl2. This is my current yml file. It sounds like I can make changes based on what you said above, one way or the other. Although, for the ZMQ part, I don't recall that port in the docker for vdl2.

```
services:
  acars_router:
    container_name: acars_router
    environment:
    - TZ="America/New_York"
    - AR_SEND_UDP_ACARS=acarshub:5550
    image: ghcr.io/sdr-enthusiasts/acars_router:latest
    labels:
    - autoheal=true
    ports:
    - 55555:15555
    - 55550:15550
    restart: always
    tmpfs:
    - /run:exec,size=64M
    - /var/log
    tty: true
  acarsdec:
    container_name: acarsdec
    devices:
    - /dev/bus/usb:/dev/bus/usb
    environment:
    - QUIET_LOGS=true
    - TZ=EST
    - SOAPYSDR=driver=rtlsdr,serial=00000001
    - GAIN=-10
    - PPM=0
    - FREQUENCIES=131.550;130.025;130.425;130.450;131.125
    - FEED_ID=
    - SERVER=acars_router
    image: ghcr.io/sdr-enthusiasts/docker-acarsdec:latest
    restart: unless-stopped
    tmpfs:
    - /run:exec,size=64M
    - /var/log:size=64M
    tty: true
  acarshub:
    container_name: acarshub
    devices:
    - /dev/bus/usb:/dev/bus/usb
    environment:
    - TZ="America/New_York"
    - ENABLE_VDLM=false
    - ENABLE_ACARS=external
    - MIN_LOG_LEVEL=3
    - TAR1090_URL=http://172.17.0.1:8078/
    - IATA_OVERRIDE=UP|UPS|United Parcel Service;GS|FTH|Mountain Aviation (Foothills);GS|EJA|ExecJet
    - ENABLE_ADSB=true
    - ADSB_LAT=
    - ADSB_LON=-
    - ADSB_URL=http://172.17.0.1:8078/data/aircraft.json
    - TAR1090_ENABLE_AC_DB=true
    - DB_SAVEALL=
    image: ghcr.io/sdr-enthusiasts/docker-acarshub:latest
    ports:
    - 80:80
    - 5550:5550/udp
    - 5555:5555/udp
    - 15550:15550
    - 15555:15555
    restart: unless-stopped
    tmpfs:
    - /database:exec,size=64M
    - /run:exec,size=64M
    - /var/log:size=64M
    tty: true
    volumes:
    - acars_data:/run/acars
version: '3.8'
volumes:
  acars_data: null
```
