### ISSUE TITLE
Duplicate entries written to SQLite DB

### ISSUE THREAD

**Issue by AlNotSteve** [sdr-enthusiasts/docker-acarshub#1111]
Hi,

My instance is writing duplicate entries into the SQLite DB.  Viewing live messages shows individual messages as expected, however.

docker-compose.yml file:

```
version: "3.8"

volumes:
  acars_data:

services:
  acarshub:
    image: ghcr.io/sdr-enthusiasts/docker-acarshub:latest
    tty: true
    container_name: acarshub
    restart: always
    devices:
      - /dev/bus/usb:/dev/bus/usb
    ports:
      - 8080:80
      - 5550:5550/udp
      - 5555:5555/udp
      - 15550:15550
      - 15555:15555
    volumes:
      - /opt/acarshub/acars_data:/run/acars
    tmpfs:
      - /database:exec,size=64M
      - /run:exec,size=64M
      - /var/log:size=64M
    environment:
      - TZ=Australia/Brisbane
      - ENABLE_VDLM=external
      - ENABLE_ACARS=false
      - MIN_LOG_LEVEL=3
  #      - TAR1090_URL=http://tar1090
  #      - IATA_OVERRIDE=UP|UPS|United Parcel Service;GS|FTH|Mountain Aviation (Foothills);GS|EJA|ExecJet
  #      - ENABLE_ADSB=true
  #      - ADSB_LAT=
  #      - ADSB_LON=
  #      - ADSB_URL=

  acars_router:
    image: ghcr.io/sdr-enthusiasts/acars_router:latest
    labels:
      - "autoheal=true"
    tty: true
    ports:
      - 55555:15555
      - 55550:15550
    container_name: acars_router
    restart: always
    environment:
      - TZ=${FEEDER_TZ}
      - AR_SEND_UDP_VDLM2=acarshub:5555
    tmpfs:
      - /run:exec,size=64M
      - /var/log

```
Any ideas what's going on?

Thanks!
